module.exports = `
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width:100%;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody class="mcnFollowBlockOuter"><tr><td align="center" valign="top" style="padding:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowBlockInner"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentContainer" style="min-width:100%;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" style="padding-left:9px;padding-right:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;background-color:#0f0;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContent"><tbody><tr><td align="center" valign="top" style="padding-top:9px;padding-right:9px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="top" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><!--[if mso]>
                <table align="center" border="0" cellspacing="0" cellpadding="0">
                <tr>
                <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://twitter.com/hackernoon" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-twitter-48.png" alt="Twitter" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://web.facebook.com/hackernoon/" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-facebook-48.png" alt="Facebook" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://www.instagram.com/hackernoon/" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-instagram-48.png" alt="Link" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://open.spotify.com/show/783uO1WFfFxF44lLbizUJf" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-spotify-48.png" alt="Spotify" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://www.youtube.com/c/hackernoon" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-youtube-48.png" alt="YouTube" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://pinterest.com/hackernoon/" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-pinterest-48.png" alt="Pinterest" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://www.reddit.com/r/hackernoon/" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-reddit-48.png" alt="Reddit" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://github.com/hackernoon" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-github-48.png" alt="GitHub" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:10px;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="https://hackernoon.com/feed" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-rss-48.png" alt="RSS" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                    <td align="center" valign="top">
                    <![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td valign="top" style="padding-right:0;padding-bottom:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%" class="mcnFollowContentItemContainer"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="left" valign="middle" style="padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:9px;mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><tbody><tr><td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><a href="mailto:stories@hackernoon.com" target="_blank" style="mso-line-height-rule:exactly;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/dark-forwardtofriend-48.png" alt="Email" style="display:block;border:0;height:auto;outline:0;text-decoration:none;-ms-interpolation-mode:bicubic" height="24" width="24" class=""></a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!--[if mso]>
                    </td>
                    <![endif]--><!--[if mso]>
                </tr>
                </table>
                <![endif]--></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>
`;